package migrations

func init() {
	migrateSQL := `
CREATE TABLE issuers
(
    id      int       NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_issuers PRIMARY KEY,
    moex_id int       NOT NULL,
    name    text      NOT NULL,
    inn     text      NULL,
    okpo    text      NULL,
    created timestamp NOT NULL,
    updated timestamp NOT NULL
);

CREATE UNIQUE INDEX ix_issuers_moex_id ON issuers (moex_id);
CREATE UNIQUE INDEX ix_issuers_moex_inn ON issuers (inn) WHERE inn IS NOT NULL;
CREATE UNIQUE INDEX ix_issuers_moex_okpo ON issuers (okpo) WHERE okpo IS NOT NULL;

CREATE TABLE bonds
(
    id                   int       NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_bonds PRIMARY KEY,
    moex_id              int       NOT NULL,
    issuer_id            int       NOT NULL CONSTRAINT "FK_bond_issuer" REFERENCES issuers ON DELETE CASCADE,
    security_id          text      NOT NULL,
    short_name           text      NOT NULL,
    full_name            text      NOT NULL,
    isin                 text      NOT NULL,
    is_traded            boolean   NOT NULL,
    qualified_only       boolean   NOT NULL,
    type                 text      NOT NULL,
    primary_board_id     text      NOT NULL,
    marketprice_board_id text      NOT NULL,
    initial_face_value   numeric   NOT NULL,
    face_unit            text      NOT NULL,
    issue_date           date      NULL,
    maturity_date        date      NULL,
    created              timestamp NOT NULL,
    updated              timestamp NOT NULL
);

CREATE UNIQUE INDEX ix_bonds_moex_id ON bonds (moex_id);
CREATE UNIQUE INDEX ix_bonds_security_id ON bonds (security_id);
CREATE UNIQUE INDEX ix_bonds_isin ON bonds (isin);
CREATE INDEX ix_bonds_is_traded ON bonds (is_traded);
CREATE INDEX ix_bonds_qualified_only ON bonds (qualified_only);
CREATE INDEX ix_bonds_type ON bonds (type);
CREATE INDEX ix_bonds_issue_date_asc ON bonds (issue_date ASC);
CREATE INDEX ix_bonds_issue_date_desc ON bonds (issue_date DESC);
CREATE INDEX ix_bonds_maturity_date_asc ON bonds (maturity_date ASC);
CREATE INDEX ix_bonds_maturity_date_desc ON bonds (maturity_date DESC);

CREATE TABLE payments
(
    id                 int       NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_payments PRIMARY KEY,
    bond_id            int       NOT NULL CONSTRAINT "FK_bond_payment" REFERENCES bonds ON DELETE CASCADE,
    type               text      NOT NULL,
    date               date      NOT NULL,
    value              numeric   NOT NULL,
    value_percent      numeric   NOT NULL,
    value_rub          numeric   NOT NULL,
    coupon_record_date date      NULL,
    coupon_start_date  date      NULL,
    offer_price        numeric   NULL,
    offer_value        numeric   NULL,
    offer_agent        text      NULL,
    offer_type         text      NULL,
    created            timestamp NOT NULL,
    updated            timestamp NOT NULL
);

CREATE INDEX ix_payments_type ON payments (type);
CREATE INDEX ix_payments_date_asc ON payments (date ASC);
CREATE INDEX ix_payments_date_desc ON payments (date DESC);

CREATE TABLE marketdata
(
    id                int       NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_marketdata PRIMARY KEY,
    bond_id           int       NOT NULL CONSTRAINT "FK_bond_payment" REFERENCES bonds ON DELETE CASCADE,
    time              timestamp NOT NULL,
    face_value        numeric   NULL,
    currency          text      NULL,
    last              numeric   NULL,
    last_change       numeric   NULL,
    close_price       numeric   NULL,
    legal_close_price numeric   NULL,
    accrued_interest  numeric   NULL
);
`

	rollback := `
DROP TABLE marketdata;
DROP TABLE payments;
DROP TABLE bonds;
DROP TABLE issuers;
`

	registerSQL("0_initial", migrateSQL, rollback)
}
