package migrations

func init() {
	migrateSQL := `
CREATE TABLE search
(
    id      int      NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_search PRIMARY KEY,
    bond_id int      NOT NULL CONSTRAINT "FK_bond_search" REFERENCES bonds ON DELETE CASCADE,
    vector  tsvector NOT NULL
);

CREATE INDEX ix_search_gin ON search USING gin (vector);

CREATE OR REPLACE PROCEDURE proc_rebuild_search_index()
    LANGUAGE sql
AS
$$

DELETE
FROM search
WHERE TRUE::bool;

WITH cte_bonds AS (
    SELECT *
    FROM bonds
    WHERE is_traded = TRUE
),
cte_texts AS (
    SELECT id, isin AS text
    FROM bonds
    UNION
    SELECT id, short_name AS text
    FROM bonds
    UNION
    SELECT id, full_name AS text
    FROM bonds
    UNION
    SELECT id, security_id AS text
    FROM bonds
    UNION
    SELECT bonds.id, i.name AS text
    FROM bonds
    INNER JOIN issuers i ON i.id = bonds.issuer_id
)
INSERT
INTO search (bond_id, vector)
SELECT id, TO_TSVECTOR(text)
FROM cte_texts;

$$;

CALL proc_rebuild_search_index();
`

	rollback := `
DROP PROCEDURE IF EXISTS proc_rebuild_search_index;
DROP TABLE IF EXISTS search;
`

	registerSQL("1_add_search", migrateSQL, rollback)
}
