name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: download
      run: go mod download

    - name: format
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

    - name: vet
      run: go vet ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
          version: latest
          skip-go-installation: true

    - name: build
      run: go build -v ./...

    - name: test
      run: go test -v ./...
